### ISSUE TITLE
PHP: class variables cycling

### ISSUE THREAD

**Issue by pik4ez** [seletskiy/vim-pythonx#5]
When cycle through class variables, context is not considered.

    protected $_someVar;

Now inside function:

    public function getSomeVar() {
        return <HERE> // if you press <C-L>, $_someVar appears
    }

There should be some mechanism to consider context:
* for class variables, $this->_var form must be used
* for constants: self::VAR

**Comment by seletskiy** [comment]
Why not to use snipet:  
```
rt -> return $this->_`!p snip.rv=get_last_used_var(...)`
```

**Comment by pik4ez** [comment]
It limits flexibility and usefulness of vars cycling.

I want to use variables cycling when:
* assign variable: $this->_someVar = 'some value';
* pass variable as argument: someMethod($this->_someVar);
* return var: return $this->_someVar;
* any other thing anyone can do with variables.

So, I don't agree I should have a snippet for every such case.

**Comment by kovetskiy** [comment]
Must be solved. Please, try again with new version.
